class_name AudioEntry
extends Resource
## One sound in a theme's AudioManifest (Audio Bible A5). `stream` is usually an
## AudioStreamRandomizer holding the variations. Generated by tools/build_audio_manifest.gd.

## Steal / ducking priority: P0 is never stolen, P4 goes first.
enum Tier { P0, P1, P2, P3, P4 }

@export var id: StringName = &""
@export var stream: AudioStream
@export var bus: StringName = &"SFX"
@export var tier: Tier = Tier.P2
## Max simultaneous voices of this sound.
@export_range(1, 8) var poly: int = 1
## Pan by screen X through a pooled AudioStreamPlayer2D.
@export var pan: bool = false
@export var loop: bool = false
## Minimum time between two starts of this sound.
@export var cooldown_ms: int = 0
## Haptics map key (hurt, slam, god, ...) fired with the sound; empty for none.
@export var haptic: StringName = &""
## Resident size of all variations (debug overlay, budget).
@export var bytes: int = 0
